core/urls.py
from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),    
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('about/', views.about, name='about'),
    path('add_coupon/', views.AddCouponView.as_view(), name = 'add_coupon'),
    path('add_to_cart/<slug>/', views.add_to_cart,name = 'add_to_cart'),
    path('remove_from_cart/<slug>/', views.remove_from_cart,name = 'remove_from_cart'),
    path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart,name = 'remove_single_item_from_cart'),
    path('add_item_to_cart/<slug>/', views.add_single_item_to_cart,name = 'add_single_item_to_cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundFunds.as_view(), name='request-refund')

]

online_store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('allauth.account.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse, redirect
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('S', 'Shirts'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)


LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug': self.slug
        })
    

# remove blank and null after login credentials
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                            on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
       return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price() 


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_amount(self):
        total = 0 
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False, blank=True, null=True)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Addresses'

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.pk}"

core/views.py
import random
import string

from django.conf import settings
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone

from .models import Item, OrderItem, Order, Address, Payment, Coupon, Refund
from .forms import CheckoutForms, CouponForm, RefundForm

import random 
import string
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

# creating a random sequence of characters for the reference code
def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))

def is_valid_form(values):
    valid = True
    for field in values:
        if field == "":
            valid = False
    return valid


class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForms()
            context = {
                'form': form, 
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }

            shipping_address_qs = Address.objects.filter(
                user = self.request.user,
                address_type = 'S',
                default = True
            )
            if shipping_address_qs.exists():
                context.update({'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user = self.request.user,
                address_type = 'B',
                default = True
            )
            if billing_address_qs.exists():
                context.update({'default_billing_address': billing_billing_qs[0]})

            return render(self.request, "core/checkout.html", context)
        except:
            messages.info(self.request, "You do not have an active order")
            return redirect("core:checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForms(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                #Shipping address code
                use_default_shipping = form.cleaned_data.get('use_default_shipping')
                if use_default_shipping:
                    print('Using the default shipping address')
                    address_qs = Address.objects.filter(
                        user = self.request.user,
                        address_type = 'S',
                        default = True
                    )
                    if address_qs.exist():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(self.request, "No default shipping address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new address for the operations")
                    shipping_address = form.cleaned_data.get('street_address')
                    shipping_address2 = form.cleaned_data.get('apartment_address')
                    shipping_country = form.cleaned_data.get('country')
                    shipping_zip_code = form.cleaned_data.get('zip_code')
                    payment_option = form.cleaned_data.get('payment_option')

                    if is_valid_form([shipping_address, shipping_country, shipping_zip_code]):
                        shipping_address = Address(
                            user = self.request.user,
                            street_address = shipping_address,
                            apartment_address = shipping_address2,
                            country = shipping_country,
                            zip = shipping_zip_code,
                            address_type = 'S'
                        )
                        shipping_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get('set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()
                    else:
                        messages.info(self.request, "Please fill in the required shipping address fields")

                use_default_billing = form.cleaned_data.get('use_default_billing')
                same_billing_address = form.cleaned_data.get('same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print("Using the defualt billing address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='B',
                        default=True
                    )
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default billing address available")
                        return redirect('core:checkout')
                else:
                    print("User is entering a new billing address")
                    billing_address = form.cleaned_data.get(
                        'billing_address')
                    billing_address2 = form.cleaned_data.get(
                        'billing_address2')
                    billing_country = form.cleaned_data.get(
                        'billing_country')
                    billing_zip_code = form.cleaned_data.get('billing_zip')

                    if is_valid_form([billing_address, billing_country, billing_zip]):
                        billing_address = Address(
                            user=self.request.user,
                            street_address=billing_address,
                            apartment_address=billing_address2,
                            country=billing_country,
                            zip=billing_zip_code,
                            address_type='B'
                        )
                        billing_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get(
                            'set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required billing address fields")

                payment_option = form.cleaned_data.get('payment-option')

                if payment_option == "S":
                    return redirect('core:payment', payment_option="Stripe")
                elif payment_option == "P":
                    return redirect('core:payment', payment_option="Paypal")
                elif payment_option == "D":
                    return redirect('core:payment', payment_option="Debit card")
                else:
                    messages.warning(self.request, "Failed checkout")
                    return redirect('core:checkout')

        except ObjectDoesNotExist:
            messages.warning(self.request, "you don't have items in your cart")
            return redirect('core:order-summary')


class PaymentView(View):
    def get(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        if order.billing_address:
            context = {
                'order': order,
                'DISPLAY_COUPON_FORM': False
            }
            return render(self.request, 'core/payment.html', context)
        else: 
            messages.warning(self.request, "you don't have a billing address")
            return redirect('core:checkout')

    def post(self, *args, **kwargs):
        order = Order.objects.get(user=self.request.user, ordered=False)
        token = self.request.POST.get('stripeToken')
        amount = int(order.get_total_amount() * 100)

        try:
            # Use Stripe's library to make requests...
            charge = stripe.Charge.create(
                amount = amount,
                currency="usd",
                source=token,
            )

            # Creating payment order 
            payment = Payment()
            payment.stripe_charge_id = charge['id']
            payment.user = self.request.user
            payment.amount = order.get_total_amount()
            payment.save()

            # adding the order to the payment but first updating after each order
            order_items = order.items.all()
            order_items.update(ordered=True)
            for item in order_items:
                item.save()

            order.ordered = True
            order.payment = payment
            order.ref_code = create_ref_code()
            order.save()

            messages.warning(self.request, "Yout Order has been successful")
            return redirect("/")

core/templates/core/about.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
    <h1>Blog About Page!</h1>
{% endblock content %}

core/templates/core/footer.html
<!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
  
<body>

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt=""> -->
                <img src="{{item.image.url}}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src={% static "js/jquery-3.4.1.min.js" %}></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src={% static "js/popper.min.js" %}></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src={% static "js/bootstrap.min.js" %}></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

{% endblock content %}

core/templates/core/item_list.html
{% extends "base.html" %}

{% block content %}
<h2>Here is the list of items</h2>

{% for item in items %}
    {{ item }}
{% endfor %}
{% endblock %}

core/templates/core/navbar.html
{% load cart_template_tags %}
{% load static %}
<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
        <img src="{% static 'core/images/logo-1.jpg' %}" alt="Logo" width="38" height="38">
        <strong class="black-text">Art & Design</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:about' %}">About</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

core/templates/core/order_snippet.html
<div class="col-md-13 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Items in yout Cart</span>
      <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
      {% for order_item in order.items.all  %}
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title }}</h6>
          <small class="text-muted">{{ order_item.item.description }}</small>
        </div>
        <span class="text-muted">{{ order_item.get_final_price }}</span>
      </li>
      {% endfor %}
      {% if order.coupon %}
      <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
          <h6 class="my-0">Promo code</h6>
          <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
      </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total_amount }} </strong>
      </li>
    </ul>
    <!-- Cart -->
    <!-- Promo code -->
    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add_coupon' %}" method="POST">
      <!-- add csrf token and find the error -->
      <div class="input-group">
        {{ couponform.code }}
        <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
      </div>
    </form>
    {% endif %}
  <!-- Promo code -->
  </div>

core/templates/core/order_summary.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
  
<body>

  <!--Main layout-->
  <main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h1>Product Summary</h1>
            <hr>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item Title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Purchase Price</th>
                </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url 'core:remove_single_item_from_cart' order_item.item.slug %}" ><i class="fas fa-minus mr-2" ></i></a>    
                        {{ order_item.quantity }}
                        <a href="{% url 'core:add_single_item_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2" ></i></a>  
                    </td>
                    <td>
                        {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price}}
                            <span class="badge badge-primary">(Saving ${{ order_item.get_amount_saved }})</span>
                          {% else %}
                            ${{ order_item.get_total_item_price }}
                        {% endif %}
                        <a href="{% url 'core:remove_from_cart' order_item.item.slug %}">
                            <i  style="color: red" class="fas fa-trash float-right"></i>
                        </a>
                    </td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan="5" ><b>Your cart is empty</b></td>                   
                </tr>
                <tr>
                    <td colspan="5">
                    <a class="btn btn-primary float-right" href='/'>Continue Shopping</a>
                    </td>
                </tr>
            {% endfor %}
            {% if object.coupon %}
                <tr>
                    <td colspan="4"><b>Coupon</b></td>
                    <td><b>-${{ object.coupon.amount }}</b></td>
                </tr>
            {% endif %}
            {% if object.get_total_amount %}
                <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td><b>${{ object.get_total_amount }}</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                        <a class="btn btn-warning float-right ml-2" href='/checkout/'>Proceed to Checkout</a>
                        <a class="btn btn-primary float-right" href='/'>Continue Shopping</a>

                    </td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    </div>
    </main>
  <!--Main layout-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src={% static "js/jquery-3.4.1.min.js" %}></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src={% static "js/popper.min.js" %}></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src={% static "js/bootstrap.min.js" %}></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

{% endblock content %}
 